spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
sprindoc:
  default-produces-media-type: application/json

server:
  servlet:
    context:
      context-path: /api/v1
