spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

#Solved error
server:
  servlet:
    context-path: /api/v1



logging:
  level:
    org.springframework.security: DEBUG
